[package]
name = "xvm"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.15"
iced-x86 = "1.21.0"
libc = "0.2.169"
lazy_static = "1.5.0"
sdl2 = { version = "0.37.0", features = ["ttf", "use-pkgconfig", "static-link"] }